version: '3'

services:
  app:
    container_name: ${NomeContainerAplicacao}
    build:
      dockerfile: ./internal/build/docker/app.dockerfile
    env_file:
      - .env
    ports:
      - ${PortaApi}:${PortaApi}
