version: '3'

services:
  banco_postgres:
    container_name: ${NomeContainerBancoPostgres}
    image: "postgres"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORTA}:5432

  app:
    container_name: ${NomeContainerAplicacao}
    build:
      dockerfile: ./internal/build/docker/app.dockerfile
    env_file:
      - .env
    ports:
      - ${PortaApi}:${PortaApi}
    depends_on:
      - banco_postgres
